package org.abhishekjha.projectEuler;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * $$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * Let us list the factors of the first seven triangle numbers:
 *  1 : 1
 *  3 : 1,3
 *  6 : 1,2,3,6
 * 10 : 1,2,5,10
 * 15 : 1,3,5,15
 * 21 : 1,3,7,21
 * 28 : 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 */

public class HighlyDivisibleTriangularNumber {
    static long nthTriangularNumber(long n) {
        return n*(n+1)/2;
    }
    static long numberOfDivisors(long n) {
        long count = 0;
        for (long i = 1; i * i <= n; i++) {
            if (n % i == 0) {
                count++;
                if (n / i != i) {
                    count++;
                }
            }
        }
        return count;
    }

    static long solve(long divisorLimit) {
        long n = 1;
        while(true) {
            long num = nthTriangularNumber(n);
            if (numberOfDivisors(num) > divisorLimit) {
                return num;
            }
            n++;
        }
    }

    public static void main(String[] args) {
        long divisorLimit = 500;
        long result = solve(divisorLimit);
        System.out.println("The first triangular number to have over " + divisorLimit + " divisors is: " + result);
    }
}
